import React, { useState, useEffect } from 'react';
import { Volume2, VolumeX, Sparkles, RefreshCw, BookOpen } from 'lucide-react';
import { generateStory } from '../services/geminiService';

export default function StorytellerPanel({ destination, apiKey }) {
  const [story, setStory] = useState(null);
  const [loading, setLoading] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);
  const [speechUtterance, setSpeechUtterance] = useState(null);

  const fetchNewStory = async () => {
    setLoading(true);
    // Stop any speech playing
    if (window.speechSynthesis) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    }
    const data = await generateStory(destination.id, apiKey);
    setStory(data);
    setLoading(false);
  };

  useEffect(() => {
    fetchNewStory();
    return () => {
      if (window.speechSynthesis) {
        window.speechSynthesis.cancel();
      }
    };
  }, [destination.id, apiKey]);

  // Set up speech synthesis
  useEffect(() => {
    if (story && window.speechSynthesis) {
      const u = new SpeechSynthesisUtterance(story.narration);
      u.rate = 0.95; // slightly slower for dramatic effect
      u.onend = () => setIsPlaying(false);
      u.onerror = () => setIsPlaying(false);
      setSpeechUtterance(u);
    }
  }, [story]);

  const toggleSpeech = () => {
    if (!window.speechSynthesis || !speechUtterance) {
      alert("Text-to-speech is not supported on this browser.");
      return;
    }

    if (isPlaying) {
      window.speechSynthesis.cancel();
      setIsPlaying(false);
    } else {
      window.speechSynthesis.speak(speechUtterance);
      setIsPlaying(true);
    }
  };

  if (loading) {
    return (
      <div className="space-y-4 py-12 flex flex-col items-center justify-center animate-pulse">
        <BookOpen className="w-8 h-8 text-zinc-300 dark:text-zinc-700 animate-spin" />
        <div className="h-4 bg-zinc-200 dark:bg-zinc-800 rounded w-1/3"></div>
        <div className="h-3 bg-zinc-200 dark:bg-zinc-800 rounded w-1/2"></div>
      </div>
    );
  }

  return (
    <div className="max-w-2xl mx-auto space-y-6 animate-fade-in">
      
      {/* Narrative Card */}
      <div className="bg-zinc-950 dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-3xl p-6 md:p-8 shadow-sm space-y-6 relative overflow-hidden">
        
        {/* Soft background glow */}
        <div className="absolute -top-12 -right-12 w-32 h-32 bg-emerald-500/5 dark:bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />

        {/* Header controls */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 font-semibold text-xs tracking-wider uppercase">
            <BookOpen className="w-4 h-4" />
            <span>Immersive Audio Story</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={toggleSpeech}
              className={`p-2 rounded-xl transition-all duration-300 flex items-center gap-1.5 text-xs font-semibold ${
                isPlaying 
                ? 'bg-emerald-500 text-white shadow-md shadow-emerald-500/20' 
                : 'bg-zinc-100 dark:bg-zinc-800 text-zinc-700 dark:text-zinc-300 hover:bg-zinc-200 dark:hover:bg-zinc-700'
              }`}
              title={isPlaying ? "Mute Story" : "Listen to Story"}
            >
              {isPlaying ? <VolumeX className="w-4 h-4" /> : <Volume2 className="w-4 h-4" />}
              <span>{isPlaying ? 'Mute' : 'Listen'}</span>
            </button>

            {apiKey && (
              <button
                onClick={fetchNewStory}
                className="p-2 bg-zinc-100 dark:bg-zinc-800 text-zinc-500 hover:text-zinc-100 dark:hover:text-zinc-200 rounded-xl hover:bg-zinc-200 dark:hover:bg-zinc-700 transition-colors"
                title="Regenerate Narrative"
              >
                <RefreshCw className="w-4 h-4" />
              </button>
            )}
          </div>
        </div>

        {/* Narrative Text */}
        <div className="space-y-4">
          <h2 className="text-2xl font-extrabold text-zinc-950 dark:text-zinc-50 tracking-tight leading-tight">
            {story?.title}
          </h2>
          <p className="text-base text-zinc-700 dark:text-zinc-300 leading-relaxed font-sans font-light select-text">
            {story?.narration}
          </p>
        </div>

        {/* Cultural Essence Pill */}
        <div className="pt-2 border-t border-zinc-100 dark:border-zinc-800/80 flex items-center justify-between text-xs text-zinc-500 dark:text-zinc-400">
          <span className="flex items-center gap-1">
            <Sparkles className="w-3.5 h-3.5 text-emerald-500" />
            Story generated by AuraQuest AI
          </span>
          <span className="font-mono text-[10px] bg-zinc-100 dark:bg-zinc-800 px-2 py-0.5 rounded">
            Approx. {story?.audioLength || '1.5 min'}
          </span>
        </div>

      </div>

    </div>
  );
}
